production_information:
  line: SSBR
  grade: M2520
  save_meta_dir: ./tests/results/metadata
  save_image_dir: ./tests/results/images
  return_mode: anomaly

baler_classification:
  classifier:
    checkpoint: ../BalerClassification/checkpoints/BR-A/1208_paired/best_model.pth
    img_size: 224
    num_classes: ~
    class_names:
      0: "1"
      1: "3"

defect_detection:
  anomalyclip:
    checkpoint: ../DefectDetection/checkpoints/anomalyclip/9_12_4_mvtec+F1038-F2150-M2520/epoch_15.pth
    imgsz: 512 # 32*16
    threshold: 0.25
    min_area: 0

  classifier:
    checkpoint: ../DefectDetection/checkpoints/classify/weights/SSBR/_intergrated/weights/best.pt
    imgsz: 224 # 32*7
    threshold: 0.8

  bgremover:
    checkpoint: ../DefectDetection/checkpoints/segment/weights/rmbg/all/weights/best.pt
    imgsz: 160 # 32*5

  segmenter:
    checkpoint: ../DefectDetection/checkpoints/segment/weights/yolo_seg/SSBR_ALL/weights/best.pt
    imgsz: 224 # 32*7
    threshold: 0.0

  show:
    anomaly_map: false
    anomaly_score: true
    foreground: false
    anomaly_regions_polygon: true
    anomaly_regions_bbox: true
    segmentation_regions_polygon: false
    segmentation_regions_bbox: false
    show_pass_classes: false