production_information:
  line: SSBR
  grade: M2520
  save_meta_dir: ./tests/results/metadata
  save_image_dir: ./tests/results/images

baler_classification:
  classifier:
    checkpoint: ../BalerClassification/checkpoints/BR-A/1208_paired/best_model.pth
    img_size: 224
    num_classes: ~

defect_detection:
  anomalyclip:
    checkpoint: ../DefectDetection/checkpoints/anomalyclip/9_12_4_mvtec_anomaly_detection+BR-A_1208+BR-C_1280/epoch_15.pth
    imgsz: 512 # 32*12
    threshold: 0.25
    min_area: 0

  classifier:
    checkpoint: ../DefectDetection/checkpoints/classify/weights/BR/BR-A_1208_BR-C_1280/weights/best.pt
    imgsz: 32 # 32*1
    threshold: 0.8

  bgremover:
    checkpoint: ../DefectDetection/checkpoints/segment/weights/rmbg/all/weights/best.pt
    imgsz: 160 # 32*5

  segmenter:
    checkpoint: ../DefectDetection/checkpoints/segment/weights/yolo_seg/BR-A_1208_BR-C_1280/weights/best.pt
    imgsz: 224 # 32*7
    threshold: 0.0

  show:
    anomaly_map: false
    anomaly_score: true
    foreground: true